### ISSUE TITLE
docker run with latest image fails

### ISSUE THREAD

**Issue by hacker-h** [jufabeck2202/HskaFreeRoom#4]
I get the following output:
```
$ docker run kickbeak/hskafreeroom
current free rooms:
Error: Request failed with status code 400
    at createError (/usr/lib/node_modules/hskafreeroom/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/hskafreeroom/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/hskafreeroom/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by hacker-h** [comment]
This issue seems to appear only on weekends when there is no timetable available,
maybe the api is broken.
However this should be catched e.g. by returning a list of all the rooms contained in any timetable.

**Comment by jufabeck2202** [comment]
should be fixed with the latest build #
